
  version: '3.8'

  services:
    postgres-db:
      image: postgres:15
      container_name: factoo-postgres
      environment:
        - POSTGRES_USER=factoo
        - POSTGRES_PASSWORD=factoo
        - POSTGRES_DB=factoo_db
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      restart: unless-stopped

  volumes:
    postgres_data:
