spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/factoo_db
    username: factoo
    password: factoo
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE